name: flutter_zoom_box
description: A box that makes child widgets zoomable and draggable inside container like box.
version: 0.1.2
homepage: https://daehyeonnam.github.io
repository: https://github.com/DaeHyeonNam/flutter_zoom_box

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: any
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.virtually.flutter_zoom_box
        pluginClass: FlutterZoomBox
      ios:
        pluginClass: FlutterZoomBox
